// @title Dwello-api
// @version 1.0
// @description This is a sample server.
// @host localhost:8080
// @BasePath /
package main

import (
	"dwello-api/config"
	"dwello-api/routes"
	"log"

	_ "dwello-api/docs" // docs generated by Swag CLI

	fiberSwagger "github.com/swaggo/fiber-swagger"

	"github.com/gofiber/fiber/v2"
)

func main() {
	// Initialize the database connection
	config.ConnectDB()
	defer config.DisconnectDB() // Ensure the client disconnects when the program exits

	app := fiber.New()
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	routes.Setup(app) // Setup all routes

	log.Fatal(app.Listen(":8080"))
}
